name: Build Ubuntu

on: [push]

jobs:
  ubuntu:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: sudo tools/debian-setup.sh --install-optional --install-test-deps --install-deb-deps python3-pip -y
      - name: Mkdir
        run: mkdir build
      - name: Cmake
        working-directory: build
        run: cmake -GNinja ..
        env:
#          PLATFORM: x64
#          WIRESHARK_BASE_DIR: C:/wireshark-libs
#          QT5_BASE_DIR: C:/Qt/5.12.3/msvc2017_64
          WIRESHARK_BUILD_WITH_QT5: 1
      - name: Build
        run: ninja
        working-directory: build
#      - name: Build test-programs
#        run: ninja test-programs
#        working-directory: build
#      - name: Set up Python 3.8
#        uses: actions/setup-python@v1
#        with:
#          python-version: 3.8
#      - name: Install pytest
#        run: pip install pytest pytest-xdist
#      - name: Run tests
#        env:
#          PYTEST_ADDOPTS: --skip-missing-programs=rawshark
        # Remove the XDG_CONFIG_HOME variable and ensure that tshark reads configurations from the home directory
        # which created by pytest, and test cases will success in Ubuntu System.
#        run: |
#          unset XDG_CONFIG_HOME
#          pytest
#        working-directory: build
      - name: Build debian pkg
        run: dpkg-buildpackage -b -us -uc -jauto
      - name: Move deb packages
        run: |
          mkdir deb
          mv ../*.deb deb
      - name: Upload deb packages
        uses: actions/upload-artifact@v1
        with:
          name: ubuntu-packages
          path: |
            deb
            build/run
